<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\icon2.ico</ApplicationIcon>
    <AssemblyName>BetterCrewLinkKai.DotNet</AssemblyName>
    <RootNamespace>BetterCrewLinkKai.DotNet</RootNamespace>
    <AssemblyTitle>BetterCrewLinkKai.net beta</AssemblyTitle>
    <Product>BetterCrewLinkKai.net beta</Product>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\icon2.ico" />
    <Resource Include="Assets\icon2.png" />
    <Resource Include="Assets\avatar\player-template.png" />
    <Resource Include="Assets\avatar\ghost-template.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="SIPSorcery" Version="8.*" />
    <PackageReference Include="SocketIOClient" Version="3.1.2" />
  </ItemGroup>

</Project>
